# _config.yml

defaults:
  - scope:
      path: "" # empty string means all files in project
    values:
      layout: default
      title: Steven Chang
      url: "https://zminsc.github.io"
      baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

